---
- name: Deploy webserver (nginx or apache)
  hosts: webservers
  become: yes
  vars:
    webserver: nginx    # valeur par défaut ; override avec -e webserver=apache
    site_content_nginx: "<h1>Hello from Nginx</h1>"
    site_content_apache: "<h1>Hello from Apache</h1>"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install nginx when selected
      apt:
        name: nginx
        state: present
      when: webserver == 'nginx'

    - name: Install apache when selected
      apt:
        name: apache2
        state: present
      when: webserver == 'apache'

    - name: Start nginx when selected
      service:
        name: nginx
        state: started
      when: webserver == 'nginx'

    - name: Start apache when selected
      service:
        name: apache2
        state: started
      when: webserver == 'apache'

    - name: Deploy page for nginx
      copy:
        content: "{{ site_content_nginx }}"
        dest: /var/www/html/index.html
        owner: www-data
        mode: '0644'
      when: webserver == 'nginx'

    - name: Deploy page for apache
      copy:
        content: "{{ site_content_apache }}"
        dest: /var/www/html/index.html
        owner: www-data
        mode: '0644'
      when: webserver == 'apache'
