---
- name: Mettre à jour et déployer Apache
  hosts: webservers
  become: yes
  vars:
    site_content: "<h1>Bienvenue — Apache déployé par Ansible</h1>"

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install apache2
      apt:
        name: apache2
        state: present
      notify: restart apache

    - name: Ensure apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy index.html
      copy:
        content: "{{ site_content }}"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      notify: restart apache
